import type {
  BodyRegion,
  DifferentialLikelihood,
  FindingSignificance,
  LaymanFinding,
  LaymanFindingSignificance,
  LaymanOutput,
  ProfessionalOutput,
  ScanDifferential,
  ScanFinding,
  ScanImageQuality,
  ScanInterpretationResult,
  ScanModality,
  ScanUrgency,
} from "@/types/scan";

/** Words that must never appear as standalone assertions in layman output. */
const BANNED_REPLACEMENTS: Array<[RegExp, string]> = [
  [/\bdefinitely\b/gi, "likely"],
  [/\bcertainly\b/gi, "likely"],
  [/\bconfirms?\b/gi, "suggests"],
  [/\bproves?\b/gi, "suggests"],
  [/\brules? out\b/gi, "makes less likely"],
];

const MODALITIES: ScanModality[] = [
  "xray",
  "ct",
  "mri",
  "ultrasound",
  "pet",
  "echo",
  "eeg",
  "ecg",
  "mammogram",
  "dexa",
  "angiography",
  "nuclear",
  "report_text",
];

const REGIONS: BodyRegion[] = [
  "head_brain",
  "spine",
  "chest_lungs",
  "heart_cardiac",
  "abdomen",
  "pelvis",
  "musculoskeletal",
  "breast",
  "vascular",
  "neck_thyroid",
  "orbit_eye",
  "obstetric",
  "whole_body",
  "unknown",
];

const FINDING_SIG: FindingSignificance[] = [
  "normal_variant",
  "incidental",
  "abnormal",
  "critical",
];
const LAYMAN_SIG: LaymanFindingSignificance[] = [
  "normal",
  "minor",
  "significant",
  "urgent",
];
const DIFF_LIKELIHOOD: DifferentialLikelihood[] = [
  "possible",
  "probable",
  "cannot_exclude",
];
const URGENCY: ScanUrgency[] = ["routine", "urgent", "critical"];
const QUALITY: ScanImageQuality[] = ["adequate", "suboptimal", "inadequate"];

function s(v: unknown, fallback = ""): string {
  return typeof v === "string" ? v : fallback;
}
function arr<T>(v: unknown): T[] {
  return Array.isArray(v) ? (v as T[]) : [];
}
function pick<T extends string>(v: unknown, allowed: T[], fallback: T): T {
  return typeof v === "string" && (allowed as string[]).includes(v)
    ? (v as T)
    : fallback;
}

function sanitiseLayman(text: string): string {
  let out = text;
  for (const [re, replacement] of BANNED_REPLACEMENTS) out = out.replace(re, replacement);
  // never use the word "cancer" as a standalone term in layman text
  out = out.replace(
    /\bcancer\b/gi,
    "a finding your doctor will discuss in detail",
  );
  return out;
}

function normaliseFinding(raw: unknown): ScanFinding {
  const o = (raw ?? {}) as Record<string, unknown>;
  return {
    location: s(o.location, "Unspecified location"),
    description: s(o.description),
    significance: pick(o.significance, FINDING_SIG, "abnormal"),
    characterisation: s(o.characterisation),
  };
}

function normaliseDifferential(raw: unknown): ScanDifferential {
  const o = (raw ?? {}) as Record<string, unknown>;
  return {
    diagnosis: s(o.diagnosis),
    likelihood: pick(o.likelihood, DIFF_LIKELIHOOD, "possible"),
    supportingFindings: arr<string>(o.supportingFindings).map((x) => s(x)),
    againstFindings: arr<string>(o.againstFindings).map((x) => s(x)),
  };
}

function normaliseLaymanFinding(raw: unknown): LaymanFinding {
  const o = (raw ?? {}) as Record<string, unknown>;
  return {
    area: s(o.area, "Your scan"),
    plainEnglish: sanitiseLayman(s(o.plainEnglish)),
    significance: pick(o.significance, LAYMAN_SIG, "minor"),
    analogy: o.analogy ? sanitiseLayman(s(o.analogy)) : undefined,
  };
}

function normaliseProfessional(raw: unknown): ProfessionalOutput {
  const o = (raw ?? {}) as Record<string, unknown>;
  return {
    findings: arr<unknown>(o.findings).map(normaliseFinding),
    impression: s(o.impression),
    differentials: arr<unknown>(o.differentials).map(normaliseDifferential),
    recommendations: arr<string>(o.recommendations).map((x) => s(x)),
    limitations: arr<string>(o.limitations).map((x) => s(x)),
    urgency: pick(o.urgency, URGENCY, "routine"),
  };
}

function normaliseLayman(raw: unknown): LaymanOutput {
  const o = (raw ?? {}) as Record<string, unknown>;
  return {
    summary: sanitiseLayman(s(o.summary)),
    keyFindings: arr<unknown>(o.keyFindings).map(normaliseLaymanFinding),
    whatThisMeans: sanitiseLayman(s(o.whatThisMeans)),
    nextSteps: arr<string>(o.nextSteps).map((x) => sanitiseLayman(s(x))),
    questionsForDoctor: arr<string>(o.questionsForDoctor).map((x) => s(x)),
  };
}

export interface NormaliseScanContext {
  modality: ScanModality;
  bodyRegion: BodyRegion;
  clinicalContext?: string | null;
  language?: string;
}

const DEFAULT_DISCLAIMER =
  "This interpretation is generated by AI and must be reviewed by a qualified radiologist, pathologist, or clinician before any clinical decision is made.";

export function normaliseScanResult(
  raw: unknown,
  ctx: NormaliseScanContext,
): ScanInterpretationResult {
  const o = (raw ?? {}) as Record<string, unknown>;
  const imageQuality = pick(o.imageQuality, QUALITY, "adequate");
  const professional = normaliseProfessional(o.professional);
  const layman = normaliseLayman(o.layman);

  return {
    id:
      typeof crypto !== "undefined" && "randomUUID" in crypto
        ? crypto.randomUUID()
        : `scan-${Date.now()}`,
    modality: pick(ctx.modality, MODALITIES, "xray"),
    bodyRegion: pick(ctx.bodyRegion, REGIONS, "unknown"),
    clinicalContext: ctx.clinicalContext ?? null,
    language: ctx.language ?? "en",
    imageQuality,
    imageQualityNote: o.imageQualityNote ? s(o.imageQualityNote) : undefined,
    professional,
    layman,
    indeterminateFindings: arr<string>(o.indeterminateFindings).map((x) =>
      s(x),
    ),
    criticalAlerts: arr<string>(o.criticalAlerts).map((x) => s(x)),
    cannotAssess: arr<string>(o.cannotAssess).map((x) => s(x)),
    aiConfidenceNote: s(o.aiConfidenceNote) || DEFAULT_DISCLAIMER,
    createdAt: new Date().toISOString(),
  };
}
