import type { AnalysisResult } from "@/types/report";

const PRINT_ROOT_ID = "print-target";

function statusLabel(s: string): string {
  if (s === "flagged") return "FLAGGED";
  if (s === "watch") return "TO WATCH";
  return "NORMAL";
}

function buildHtml(result: AnalysisResult): string {
  const md = result.metadata;
  const counts = result.biomarkers.reduce(
    (acc, b) => {
      acc[b.status] += 1;
      return acc;
    },
    { normal: 0, watch: 0, flagged: 0 } as Record<string, number>,
  );

  const biomarkerRows = result.biomarkers
    .map(
      (b) => `
      <div style="margin: 10px 0; padding-bottom: 8px; border-bottom: 1px solid #ddd;">
        <div style="font-weight: 600;">${b.name} — ${b.value} ${b.unit} <span style="font-weight: 400; color: #555;">(${statusLabel(b.status)}, ref ${b.referenceRange.low}–${b.referenceRange.high})</span></div>
        <div style="font-size: 12px; color: #333;">${b.plainEnglish}</div>
      </div>`,
    )
    .join("");

  const paragraphs = result.summary
    .split(/\n\n+/)
    .map((p) => `<p style="margin: 8px 0;">${p}</p>`)
    .join("");

  const questions = result.doctorQuestions
    .map((q, i) => `<li style="margin: 6px 0;">${i + 1}. ${q}</li>`)
    .join("");

  return `
    <h1 style="margin: 0 0 4px 0;">ReportRx — Lab Report Analysis</h1>
    <div style="font-size: 12px; color: #555; margin-bottom: 16px;">
      ${md.patientName ? `Patient: ${md.patientName} · ` : ""}
      ${md.reportDate ? `Date: ${md.reportDate} · ` : ""}
      ${md.labName ?? ""}
    </div>
    <div style="font-size: 13px; margin-bottom: 12px;">
      ${counts.normal} normal · ${counts.watch} to watch · ${counts.flagged} flagged
    </div>
    <h2 style="margin: 16px 0 6px 0;">Biomarkers</h2>
    ${biomarkerRows}
    <h2 style="margin: 18px 0 6px 0;">Summary</h2>
    ${paragraphs}
    <h2 style="margin: 18px 0 6px 0;">Questions for your doctor</h2>
    <ol style="padding-left: 20px;">${questions}</ol>
    <p style="font-size: 11px; color: #777; margin-top: 18px;">
      Generated by ReportRx. Informational only — not medical advice.
    </p>
  `;
}

export function downloadReportPdf(result: AnalysisResult): void {
  if (typeof window === "undefined") return;
  const existing = document.getElementById(PRINT_ROOT_ID);
  if (existing) existing.remove();
  const container = document.createElement("div");
  container.id = PRINT_ROOT_ID;
  container.innerHTML = buildHtml(result);
  document.body.appendChild(container);
  const cleanup = () => {
    container.remove();
    window.removeEventListener("afterprint", cleanup);
  };
  window.addEventListener("afterprint", cleanup);
  setTimeout(() => window.print(), 50);
}
