const NORMALIZATION_MAP: Record<string, string> = {
  hemoglobin: "hemoglobin",
  haemoglobin: "hemoglobin",
  hb: "hemoglobin",
  hgb: "hemoglobin",
  rbc: "rbc",
  "red blood cells": "rbc",
  "red blood cell count": "rbc",
  erythrocytes: "rbc",
  hct: "hematocrit",
  haematocrit: "hematocrit",
  hematocrit: "hematocrit",
  pcv: "hematocrit",
  mcv: "mcv",
  "mean corpuscular volume": "mcv",
  mch: "mch",
  "mean corpuscular hemoglobin": "mch",
  mchc: "mchc",
  "mean corpuscular hemoglobin concentration": "mchc",
  rdw: "rdw",
  "rdw-cv": "rdw",
  "rdw cv": "rdw",
  "red cell distribution width": "rdw",
  wbc: "wbc",
  "white blood cells": "wbc",
  leukocytes: "wbc",
  "total leukocyte count": "wbc",
  tlc: "wbc",
  neutrophils: "neutrophils",
  neutrophil: "neutrophils",
  "neutrophils %": "neutrophils_pct",
  "absolute neutrophil count": "anc",
  anc: "anc",
  lymphocytes: "lymphocytes",
  lymphocyte: "lymphocytes",
  "lymphocytes %": "lymphocytes_pct",
  monocytes: "monocytes",
  "monocytes %": "monocytes_pct",
  eosinophils: "eosinophils",
  "eosinophils %": "eosinophils_pct",
  basophils: "basophils",
  "basophils %": "basophils_pct",
  platelets: "platelets",
  plt: "platelets",
  "platelet count": "platelets",
  thrombocytes: "platelets",
  mpv: "mpv",
  "mean platelet volume": "mpv",
  ferritin: "ferritin",
  "serum ferritin": "ferritin",
  "serum iron": "serum_iron",
  iron: "serum_iron",
  tibc: "tibc",
  "total iron binding capacity": "tibc",
  "transferrin saturation": "transferrin_sat",
  glucose: "glucose",
  "blood glucose": "glucose",
  fbs: "glucose",
  "fasting glucose": "glucose",
  hba1c: "hba1c",
  "glycated hemoglobin": "hba1c",
  creatinine: "creatinine",
  "serum creatinine": "creatinine",
  urea: "urea",
  "blood urea": "urea",
  bun: "bun",
  "uric acid": "uric_acid",
  alt: "alt",
  sgpt: "alt",
  "alanine aminotransferase": "alt",
  ast: "ast",
  sgot: "ast",
  "aspartate aminotransferase": "ast",
  alp: "alp",
  "alkaline phosphatase": "alp",
  bilirubin: "bilirubin_total",
  "total bilirubin": "bilirubin_total",
  tsh: "tsh",
  "thyroid stimulating hormone": "tsh",
  t3: "t3",
  t4: "t4",
  "free t4": "ft4",
  ft4: "ft4",
  cholesterol: "cholesterol_total",
  "total cholesterol": "cholesterol_total",
  ldl: "ldl",
  "ldl cholesterol": "ldl",
  hdl: "hdl",
  "hdl cholesterol": "hdl",
  triglycerides: "triglycerides",
  "vitamin d": "vitamin_d",
  "25-oh vitamin d": "vitamin_d",
  "vitamin b12": "vitamin_b12",
  b12: "vitamin_b12",
  folate: "folate",
  "folic acid": "folate",
  potassium: "potassium",
  "k+": "potassium",
  sodium: "sodium",
  "na+": "sodium",
};

export function normalizeBiomarkerName(rawName: string): string {
  const cleaned = rawName
    .toLowerCase()
    .trim()
    .replace(/[()]/g, "")
    .replace(/\s+/g, " ");
  return NORMALIZATION_MAP[cleaned] ?? cleaned;
}
