/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZenoRouteImport } from './routes/zeno'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ScanV2RouteImport } from './routes/scan-v2'
import { Route as ScanResultsRouteImport } from './routes/scan-results'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultsV2RouteImport } from './routes/results-v2'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyHealthStoryRouteImport } from './routes/my-health-story'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'

const ZenoRoute = ZenoRouteImport.update({
  id: '/zeno',
  path: '/zeno',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanV2Route = ScanV2RouteImport.update({
  id: '/scan-v2',
  path: '/scan-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan-results',
  path: '/scan-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsV2Route = ResultsV2RouteImport.update({
  id: '/results-v2',
  path: '/results-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHealthStoryRoute = MyHealthStoryRouteImport.update({
  id: '/my-health-story',
  path: '/my-health-story',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRoute
  '/my-health-story': typeof MyHealthStoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/results-v2': typeof ResultsV2Route
  '/scan': typeof ScanRoute
  '/scan-results': typeof ScanResultsRoute
  '/scan-v2': typeof ScanV2Route
  '/tutorial': typeof TutorialRoute
  '/zeno': typeof ZenoRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/s/$token': typeof STokenRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRoute
  '/my-health-story': typeof MyHealthStoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/results-v2': typeof ResultsV2Route
  '/scan': typeof ScanRoute
  '/scan-results': typeof ScanResultsRoute
  '/scan-v2': typeof ScanV2Route
  '/tutorial': typeof TutorialRoute
  '/zeno': typeof ZenoRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/s/$token': typeof STokenRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof HistoryRoute
  '/my-health-story': typeof MyHealthStoryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/results-v2': typeof ResultsV2Route
  '/scan': typeof ScanRoute
  '/scan-results': typeof ScanResultsRoute
  '/scan-v2': typeof ScanV2Route
  '/tutorial': typeof TutorialRoute
  '/zeno': typeof ZenoRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/s/$token': typeof STokenRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/history'
    | '/my-health-story'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/results-v2'
    | '/scan'
    | '/scan-results'
    | '/scan-v2'
    | '/tutorial'
    | '/zeno'
    | '/auth/reset-password'
    | '/s/$token'
    | '/api/public/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/history'
    | '/my-health-story'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/results-v2'
    | '/scan'
    | '/scan-results'
    | '/scan-v2'
    | '/tutorial'
    | '/zeno'
    | '/auth/reset-password'
    | '/s/$token'
    | '/api/public/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/history'
    | '/my-health-story'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/results-v2'
    | '/scan'
    | '/scan-results'
    | '/scan-v2'
    | '/tutorial'
    | '/zeno'
    | '/auth/reset-password'
    | '/s/$token'
    | '/api/public/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  MyHealthStoryRoute: typeof MyHealthStoryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  ResultsV2Route: typeof ResultsV2Route
  ScanRoute: typeof ScanRoute
  ScanResultsRoute: typeof ScanResultsRoute
  ScanV2Route: typeof ScanV2Route
  TutorialRoute: typeof TutorialRoute
  ZenoRoute: typeof ZenoRoute
  STokenRoute: typeof STokenRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zeno': {
      id: '/zeno'
      path: '/zeno'
      fullPath: '/zeno'
      preLoaderRoute: typeof ZenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-v2': {
      id: '/scan-v2'
      path: '/scan-v2'
      fullPath: '/scan-v2'
      preLoaderRoute: typeof ScanV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-results': {
      id: '/scan-results'
      path: '/scan-results'
      fullPath: '/scan-results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results-v2': {
      id: '/results-v2'
      path: '/results-v2'
      fullPath: '/results-v2'
      preLoaderRoute: typeof ResultsV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-health-story': {
      id: '/my-health-story'
      path: '/my-health-story'
      fullPath: '/my-health-story'
      preLoaderRoute: typeof MyHealthStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  HistoryRoute: HistoryRoute,
  MyHealthStoryRoute: MyHealthStoryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  ResultsV2Route: ResultsV2Route,
  ScanRoute: ScanRoute,
  ScanResultsRoute: ScanResultsRoute,
  ScanV2Route: ScanV2Route,
  TutorialRoute: TutorialRoute,
  ZenoRoute: ZenoRoute,
  STokenRoute: STokenRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
